Repository pingcap/tiproxy, pull requests merged in 2023-10, with the labels that each got.

#376 infosync: increase timeout for `infosync` tests
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
Labels: size/S, lgtm, approved

#373 backend, net: Support compression protocol
  go.mod
  go.sum
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/authenticator_test.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/common_test.go
  pkg/proxy/backend/mock_backend_test.go
  pkg/proxy/backend/mock_client_test.go
  pkg/proxy/backend/testsuite_test.go
  pkg/proxy/net/compress.go
  pkg/proxy/net/compress_test.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/packetio.go
  pkg/proxy/net/packetio_options.go
  pkg/proxy/net/packetio_test.go
  pkg/proxy/net/proxy.go
  pkg/proxy/net/proxy_test.go
  pkg/proxy/net/tls.go
  pkg/proxy/net/tls_test.go
Labels: lgtm, approved, size/XXL

#378 net: fix packet sequence when sequence overflows
  pkg/proxy/net/compress.go
  pkg/proxy/net/compress_test.go
  pkg/proxy/net/packetio.go
  pkg/proxy/net/packetio_test.go
Labels: lgtm, approved, size/L

#382 net, config: optimize read and write packets
  conf/proxy.toml
  lib/config/proxy.go
  lib/config/proxy_test.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/common_test.go
  pkg/proxy/client/client_conn.go
  pkg/proxy/net/compress.go
  pkg/proxy/net/compress_test.go
  pkg/proxy/net/packetio.go
  pkg/proxy/net/packetio_test.go
  pkg/proxy/net/proxy.go
  pkg/proxy/net/proxy_test.go
  pkg/proxy/net/tls.go
  pkg/proxy/net/tls_test.go
  pkg/proxy/proxy.go
Labels: lgtm, approved, size/XL

#385 api: add json format response
  pkg/server/api/config.go
Labels: size/XS, lgtm, approved

#386 manager: get unicast ip only when the config one is not
  lib/util/sys/sys.go
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
Labels: lgtm, approved, size/M

#389 auth: reconnect backend
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/handshake_handler.go
Labels: lgtm, approved, size/M

#390 backend: fix duplicated import
  pkg/proxy/backend/authenticator.go
Labels: size/XS, lgtm, approved
