Repository pingcap/tiproxy, pull requests merged in 2023-09, with the labels that each got.

#354 server: print more info about build and runtime
  Makefile
  pkg/server/server.go
  pkg/util/versioninfo/versioninfo.go
Labels: lgtm, approved, size/M

#357 net, backend: fix wrong format in error packet
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/mock_backend_test.go
  pkg/proxy/net/packetio_mysql.go
  pkg/proxy/net/packetio_test.go
Labels: lgtm, approved, size/L

#359 backend: refine the error message when require TLS
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/authenticator_test.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/error.go
  pkg/proxy/backend/mock_backend_test.go
  pkg/proxy/backend/mock_proxy_test.go
Labels: lgtm, approved, size/L

#367 backend, net: support connection attrs in COM_CHANGE_USER
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/cmd_processor.go
  pkg/proxy/backend/cmd_processor_exec.go
  pkg/proxy/backend/mock_backend_test.go
  pkg/proxy/backend/mock_client_test.go
  pkg/proxy/backend/testsuite_test.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/mysql_test.go
Labels: lgtm, approved, size/XL

#370 readme: add future plans and blog link
  README.md
Labels: size/S, lgtm, approved

#372 *: fix docker file for new arg
  Makefile
  docker/Dockerfile
Labels: size/XS, lgtm, approved
