Repository pingcap/tiproxy, pull requests merged in 2023-08, with the labels that each got.

#338 fix: remove https in Dockerfile
  docker/Dockerfile
Labels: size/XS, lgtm, approved

#339 fix: remove mirrot test
  docker/Dockerfile
Labels: size/XS, lgtm, approved

#341 ctl: use versioninfo
  Makefile
  cmd/tiproxyctl/main.go
Labels: size/S, lgtm, approved

#342 fix link in readme
  README.md
Labels: size/S, lgtm, approved, needs-ok-to-test

#344 make: add clean target
  Makefile
Labels: size/XS, lgtm, approved

#348 proxy: use a real proxy conn id
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/handshake_handler.go
  pkg/proxy/backend/mock_backend_test.go
  pkg/proxy/backend/mock_client_test.go
  pkg/proxy/backend/mock_proxy_test.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/packetio_mysql.go
  pkg/proxy/net/packetio_test.go
Labels: lgtm, approved, size/M

#350 security: report warning when TLS version is below 1.2
  lib/config/proxy.go
  lib/util/security/cert.go
  lib/util/security/tls.go
  lib/util/security/tls_test.go
Labels: lgtm, approved, size/L
