Repository pingcap/tiproxy, pull requests merged in 2023-12, with the labels that each got.

#407 backend, net: add more error sources
  pkg/manager/router/router.go
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/authenticator_test.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/cmd_processor.go
  pkg/proxy/backend/cmd_processor_exec.go
  pkg/proxy/backend/cmd_processor_test.go
  pkg/proxy/backend/common_test.go
  pkg/proxy/backend/error.go
  pkg/proxy/backend/handshake_handler.go
  pkg/proxy/backend/testsuite_test.go
  pkg/proxy/client/client_conn.go
  pkg/proxy/net/compress.go
  pkg/proxy/net/error.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/mysql_test.go
  pkg/proxy/net/net_err.go
  pkg/proxy/net/packetio.go
  pkg/proxy/net/packetio_mysql.go
  pkg/proxy/net/packetio_test.go
  pkg/proxy/net/tls.go
Labels: lgtm, approved, size/XXL

#412 router, backend: check target health before redirection
  pkg/manager/router/backend_observer.go
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/manager/router/router_test.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/mock_proxy_test.go
Labels: lgtm, approved, size/XL

#415 backend, net: replace tidb/parser/mysql
  pkg/proxy/backend/authenticator_test.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/cmd_processor.go
  pkg/proxy/backend/cmd_processor_exec.go
  pkg/proxy/backend/cmd_processor_query.go
  pkg/proxy/backend/cmd_processor_test.go
  pkg/proxy/backend/error.go
  pkg/proxy/backend/handshake_handler.go
  pkg/proxy/backend/mock_client_test.go
  pkg/proxy/backend/mock_proxy_test.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/mysql_test.go
  pkg/proxy/net/server_status.go
Labels: lgtm, approved, size/L

#418 workflows: remove workflows and add codecov
  .github/workflows/common.yml
  .github/workflows/main.yml
  .github/workflows/release.yaml
  codecov.yml
Labels: lgtm, approved, size/L

#410 proxy: remove sequence check
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/authenticator_test.go
  pkg/proxy/backend/error.go
  pkg/proxy/net/packetio.go
Labels: lgtm, approved, size/M

#416 metrics, router: add more metrics
  pkg/manager/router/backend_observer.go
  pkg/manager/router/backend_observer_test.go
  pkg/manager/router/metrics.go
  pkg/metrics/backend.go
  pkg/metrics/grafana/tiproxy_summary.json
  pkg/metrics/grafana/tiproxy_summary.jsonnet
  pkg/metrics/metrics.go
  pkg/metrics/server.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/client/client_conn.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: lgtm, approved, size/XXL

#419 config: move require-backend-tls from proxy to security
  conf/proxy.toml
  lib/config/proxy.go
  lib/config/proxy_test.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/server/api/config_test.go
  pkg/server/server.go
Labels: lgtm, approved, size/L

#423 router: add customized health check function
  pkg/manager/namespace/manager.go
  pkg/manager/router/backend_observer.go
  pkg/manager/router/backend_observer_test.go
  pkg/manager/router/health_check.go
  pkg/manager/router/health_check_test.go
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/manager/router/router_test.go
Labels: lgtm, approved, size/XXL

#424 *: upgrade go version to 1.21
  go.mod
  go.sum
  lib/go.mod
  lib/go.sum
Labels: lgtm, approved, size/M

#426 api: add /debug and /metrics
  pkg/server/api/server.go
Labels: size/S, lgtm, approved

#429 router: fix status path of TiDB
  pkg/manager/router/health_check.go
Labels: size/XS, lgtm, approved

#431 metrics, config: remove pushing metrics
  conf/proxy.toml
  lib/config/proxy.go
  lib/config/proxy_test.go
  pkg/manager/config/config_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/server/api/config_test.go
  pkg/server/server.go
Labels: lgtm, approved, size/L

#435 router: fix TestConcurrency
  pkg/manager/cert/manager_test.go
  pkg/manager/router/backend_observer.go
  pkg/manager/router/backend_observer_test.go
  pkg/manager/router/health_check.go
  pkg/manager/router/health_check_test.go
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/manager/router/router_test.go
  pkg/proxy/backend/common_test.go
  pkg/proxy/backend/testsuite_test.go
Labels: lgtm, approved, size/M
