Repository pingcap/tiproxy, pull requests merged in 2023-07, with the labels that each got.

#328 chore: update OWNERS
  OWNERS
Labels: size/S

#329 *: add darwin os for goreleaser
  .goreleaser.yaml
Labels: size/XS, lgtm, approved

#330 *: fix goreleaser build
  .goreleaser.yaml
Labels: size/XS, lgtm, approved

#333 backend: fix `using password` in the error message is wrong
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/authenticator_test.go
Labels: size/S, lgtm, approved

#334 *: remove connector test in gh
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: lgtm, approved, size/M

#335 Update README.md
  README.md
Labels: size/XS, lgtm, approved, needs-ok-to-test

#301 *: remove more about tidb/parser/mysql
  .golangci.yaml
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/cmd_processor.go
  pkg/proxy/backend/cmd_processor_exec.go
  pkg/proxy/backend/cmd_processor_query.go
  pkg/proxy/backend/mock_backend_test.go
  pkg/proxy/backend/mock_client_test.go
  pkg/proxy/backend/mock_proxy_test.go
  pkg/proxy/net/auth.go
  pkg/proxy/net/header.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/mysql_test.go
  pkg/proxy/net/packetio_mysql.go
  pkg/proxy/net/packetio_test.go
Labels: lgtm, approved, size/L
