Repository pingcap/tiproxy, pull requests merged in 2023-11, with the labels that each got.

#391 backend, net: optimize read/write connection by forwarding packets
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/cmd_processor_exec.go
  pkg/proxy/backend/cmd_processor_query.go
  pkg/proxy/backend/mock_client_test.go
  pkg/proxy/net/compress.go
  pkg/proxy/net/error.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/packetio.go
  pkg/proxy/net/packetio_test.go
  pkg/proxy/net/proxy.go
  pkg/proxy/net/tls.go
  pkg/util/bufio/bufio.go
Labels: lgtm, approved, size/XXL

#388 api: add grpc and diagnostics
  go.mod
  go.sum
  pkg/server/api/config.go
  pkg/server/api/config_test.go
  pkg/server/api/debug.go
  pkg/server/api/debug_test.go
  pkg/server/api/metrics.go
  pkg/server/api/metrics_test.go
  pkg/server/api/namespace.go
  pkg/server/api/namespace_test.go
  pkg/server/api/server.go
  pkg/server/api/server_test.go
  pkg/server/server.go
Labels: lgtm, approved, size/XXL

#393 proxy: listen on additional addrs
  lib/config/proxy.go
  pkg/manager/config/manager.go
  pkg/manager/infosync/info.go
  pkg/metrics/metrics_test.go
  pkg/proxy/backend/handshake_handler.go
  pkg/proxy/client/client_conn.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: lgtm, approved, size/L

#394 backend, net: reduce memory allocation in forwarding packets
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/cmd_processor.go
  pkg/proxy/backend/cmd_processor_exec.go
  pkg/proxy/backend/cmd_processor_query.go
  pkg/proxy/backend/mock_client_test.go
  pkg/proxy/backend/mock_proxy_test.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/packetio.go
  pkg/proxy/net/packetio_test.go
  pkg/proxy/net/protocol.go
Labels: lgtm, approved, size/XL

#395 backend, net: log client versions
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/client/client_conn.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/mysql_test.go
  pkg/proxy/proxy.go
Labels: lgtm, approved, size/M

#396 config: support online reload for some config
  lib/config/namespace.go
  lib/config/namespace_test.go
  lib/config/proxy.go
  lib/config/proxy_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/proxy/backend/handshake_handler.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/server/api/namespace_test.go
  pkg/server/api/server.go
  pkg/server/server.go
Labels: lgtm, approved, size/XL

#398 backend, infosync: optimize `TestHandlerReturnError` and `TestEtcdServerDown4Sync`
  pkg/manager/infosync/info_test.go
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/mock_proxy_test.go
Labels: lgtm, approved, size/M

#400 proxy, config: add config `graceful-close-conn-timeout`
  conf/proxy.toml
  lib/config/proxy.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/server/api/config_test.go
Labels: lgtm, approved, size/L

#403 conf: use server-http-tls to specify http security | tidb-test=pr/2248
  conf/proxy.toml
  lib/config/proxy.go
  lib/config/proxy_test.go
  pkg/manager/cert/manager.go
  pkg/manager/cert/manager_test.go
  pkg/proxy/proxy.go
  pkg/server/api/config_test.go
  pkg/server/api/server.go
Labels: lgtm, approved, size/L
