Repository pingcap/tiproxy, pull requests merged in 2024-05, with the labels that each got.

#520 balance: support cpu-based balance
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/mock_test.go
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/metrics_reader_test.go
  pkg/balance/metricsreader/mock_test.go
  pkg/balance/metricsreader/query_result.go
  pkg/balance/metricsreader/query_result_test.go
  pkg/balance/policy/balance_policy.go
  pkg/balance/policy/mock_test.go
  pkg/manager/namespace/manager.go
Labels: lgtm, approved, size/XXL

#525 proxy: reject connection after graceful wait
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: lgtm, approved, size/L

#526 proxy: reject connection after graceful wait (#525)
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: lgtm, approved, size/L

#528 balance: match metric label with backend address
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/mock_test.go
  pkg/balance/metricsreader/mock_test.go
  pkg/balance/metricsreader/query_result.go
  pkg/balance/metricsreader/query_result_test.go
  pkg/balance/observer/backend_health.go
  pkg/balance/observer/backend_observer.go
  pkg/balance/observer/backend_observer_test.go
  pkg/balance/observer/health_check.go
  pkg/balance/observer/mock_test.go
  pkg/balance/policy/balance_policy.go
  pkg/balance/policy/mock_test.go
  pkg/balance/router/router.go
  pkg/balance/router/router_score.go
Labels: lgtm, approved, size/L

#529 infosync:define TiDBTopologyInfo to replace TopologyInfo in tidb/domain/infosync
  pkg/balance/observer/backend_fetcher.go
  pkg/balance/observer/backend_fetcher_test.go
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
Labels: lgtm, approved, size/M, needs-ok-to-test

#531 metricsreader, factor: fix wrong PromQL expression
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/metricsreader/metrics_reader.go
Labels: size/S, lgtm, approved

#533 backend:using exponential backoff policy for connecting to backends
  pkg/proxy/backend/backend_conn_mgr.go
Labels: size/S, lgtm, approved, needs-ok-to-test

#537 backend:using exponential backoff policy for connecting to backends (…
  pkg/proxy/backend/backend_conn_mgr.go
Labels: size/S, lgtm, approved

#536 config, balance: add config for labels
  go.mod
  go.sum
  lib/config/proxy.go
  pkg/balance/factor/factor.go
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_conn.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/mock_test.go
  pkg/balance/policy/balance_policy.go
  pkg/balance/policy/simple_policy.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_score_test.go
  pkg/manager/namespace/manager.go
  pkg/server/server.go
Labels: lgtm, approved, size/XL

#539 config, balance: support label-based balance
  lib/config/proxy.go
  pkg/balance/factor/backend.go
  pkg/balance/factor/backend_test.go
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_label.go
  pkg/balance/factor/factor_label_test.go
  pkg/balance/observer/backend_fetcher.go
  pkg/balance/observer/backend_fetcher_test.go
  pkg/balance/observer/backend_health.go
  pkg/server/api/config_test.go
Labels: lgtm, approved, size/XL

#541 factor: support memory-based balance
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
  pkg/balance/factor/mock_test.go
Labels: lgtm, approved, size/XXL
