Repository pingcap/tiproxy, pull requests merged in 2024-06, with the labels that each got.

#544 factor, metricsreader: support error-based balance
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/factor_error.go
  pkg/balance/factor/factor_error_test.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
  pkg/balance/factor/mock_test.go
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/query_result.go
  pkg/balance/metricsreader/query_result_test.go
Labels: lgtm, approved, size/XXL

#546 factor: support location-based balance
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_location.go
  pkg/balance/factor/factor_location_test.go
Labels: lgtm, approved, size/L

#548 factor: update migration speed
  pkg/balance/factor/factor_conn.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/factor_error.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/mock_test.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_score_test.go
Labels: lgtm, approved, size/L

#550 router, factor: fix the speed control of session migration
  pkg/balance/factor/factor.go
  pkg/balance/factor/factor_conn.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_error.go
  pkg/balance/factor/factor_error_test.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_health_test.go
  pkg/balance/factor/factor_label.go
  pkg/balance/factor/factor_location.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
  pkg/balance/policy/balance_policy.go
  pkg/balance/policy/simple_policy.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_score_test.go
Labels: lgtm, approved, size/XL

#552 factor, config: add configs for factors
  conf/proxy.toml
  lib/config/balance.go
  lib/config/proxy.go
  pkg/balance/factor/factor.go
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_conn.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_error.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_label.go
  pkg/balance/factor/factor_location.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/mock_test.go
  pkg/server/api/config_test.go
Labels: lgtm, approved, size/XL

#466 RFC: Multi-Factor-Based Balance
  docs/design/2024-02-01-multi-factor-based-balance.md
  docs/design/imgs/balance-cpu-usage.png
  docs/design/imgs/balance-location.png
Labels: lgtm, approved, size/L

#554 factor, config: update load balance configs
  conf/proxy.toml
  lib/config/balance.go
  lib/config/proxy.go
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_error.go
  pkg/balance/factor/factor_error_test.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_health_test.go
  pkg/balance/factor/factor_label.go
  pkg/balance/factor/factor_label_test.go
  pkg/balance/factor/factor_status.go
  pkg/balance/factor/factor_status_test.go
  pkg/server/api/config_test.go
Labels: lgtm, approved, size/XXL

#556 metrics, balance: add metrics for load balance
  lib/config/getter.go
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_location.go
  pkg/balance/factor/factor_location_test.go
  pkg/balance/factor/mock_test.go
  pkg/balance/metricsreader/mock_test.go
  pkg/balance/observer/backend_health.go
  pkg/balance/observer/backend_observer.go
  pkg/balance/observer/backend_observer_test.go
  pkg/balance/observer/mock_test.go
  pkg/balance/policy/balance_policy.go
  pkg/balance/policy/mock_test.go
  pkg/balance/policy/simple_policy.go
  pkg/balance/policy/simple_policy_test.go
  pkg/balance/router/metrics.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_score_test.go
  pkg/balance/router/router_static.go
  pkg/manager/namespace/manager.go
  pkg/metrics/balance.go
  pkg/metrics/grafana/tiproxy_summary.json
  pkg/metrics/grafana/tiproxy_summary.jsonnet
  pkg/metrics/traffic.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/metrics.go
Labels: lgtm, approved, size/XXL

#558 factor: update memory-based balance policy
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_health_test.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
Labels: lgtm, approved, size/L

#560 factor: use both average usage and latest usage in CPU-based balance
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
Labels: lgtm, approved, size/L

#561 metrics: set the Y axis of some metrics to logBase=2
  pkg/metrics/grafana/tiproxy_summary.json
  pkg/metrics/grafana/tiproxy_summary.jsonnet
Labels: lgtm, approved, size/M

#566 metricsreader: remove subscribe functions for MetricsReader
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/metrics_reader_test.go
Labels: lgtm, approved, size/L

#565 metricsreader: fix TestLocal
  pkg/balance/observer/backend_observer_test.go
Labels: size/XS, lgtm, approved

#563 factor: query Prometheus more frequently to update metrics timely
  lib/config/namespace.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
  pkg/balance/factor/mock_test.go
Labels: lgtm, approved, size/L

#569 observer: fix TiProxy reports unmarshal body in healthy check failed" when TiDB is graceful shutdown
  pkg/balance/observer/health_check.go
  pkg/balance/observer/health_check_test.go
Labels: size/S, lgtm, approved

#572 balance, metrics: fix location-based balance sometimes doesn't work
  pkg/balance/observer/backend_health.go
  pkg/balance/router/router_score_test.go
  pkg/metrics/metrics.go
Labels: size/S, lgtm, approved

#578 observer, net: read packet from SQL port in health check
  pkg/balance/observer/health_check.go
  pkg/balance/observer/health_check_test.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/mysql_test.go
Labels: lgtm, approved, size/M

#573 factor: update migration speed for factors
  pkg/balance/factor/factor.go
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_conn.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_health_test.go
  pkg/balance/factor/factor_label.go
  pkg/balance/factor/factor_location.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
  pkg/balance/factor/factor_status.go
  pkg/balance/factor/factor_status_test.go
  pkg/balance/factor/mock_test.go
  pkg/balance/policy/balance_policy.go
  pkg/balance/policy/simple_policy.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_score_test.go
Labels: lgtm, approved, size/XXL

#568 router, backend: pause session when last backend become unhealthy
  pkg/manager/router/backend_fetcher.go
  pkg/manager/router/backend_fetcher_test.go
  pkg/manager/router/backend_observer.go
  pkg/manager/router/backend_observer_test.go
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/manager/router/router_static.go
  pkg/manager/router/router_test.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/mock_backend_test.go
  pkg/proxy/backend/session_states.go
  pkg/proxy/backend/testsuite_test.go
Labels: lgtm, approved, needs-ok-to-test, size/XXL

#579 metricsreader: only report error once if Prometheus is not deployed
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/metrics_reader_test.go
Labels: lgtm, approved, size/M

#581 *: update changelog to v1.1.0
  CHANGELOG.md
Labels: size/S, lgtm, approved
