Repository pingcap/tiproxy, pull requests merged in 2024-01, with the labels that each got.

#445 config: check mod time
  Makefile
  go.mod
  go.sum
  lib/config/proxy.go
  pkg/manager/config/config.go
  pkg/manager/config/config_test.go
  pkg/manager/config/manager.go
  pkg/manager/config/manager_test.go
Labels: lgtm, approved, size/L

#446 config: revert to watch config file and fix the concurrency issue
  go.mod
  go.sum
  pkg/manager/config/config.go
  pkg/manager/config/config_test.go
  pkg/manager/config/manager.go
Labels: lgtm, approved, size/L

#437 Change MinTLSVersion to TLSv1.2
  lib/config/proxy.go
  pkg/server/api/config_test.go
Labels: size/S, lgtm, approved

#443 backend, logger: fix data race in UT
  pkg/manager/logger/manager_test.go
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/error.go
  pkg/proxy/backend/handshake_handler.go
  pkg/proxy/backend/mock_proxy_test.go
  pkg/proxy/proxy.go
Labels: lgtm, approved, size/L

#451 router: fix connection score becomes wrong when a connection closes during redirecting
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/manager/router/router_test.go
Labels: lgtm, approved, size/M

#454 log: print welcom after config init
  pkg/server/server.go
Labels: size/XS, lgtm, approved

#457 *: add changelog and update readme
  CHANGELOG.md
  README.md
Labels: lgtm, approved, size/L

#459 router: fix backend scores are not ordered
  pkg/manager/router/router_score.go
Labels: size/XS, lgtm, approved

#460 infosync: set longer duration to stabilize tests
  lib/util/retry/retry.go
  pkg/manager/infosync/info_test.go
Labels: size/S, lgtm, approved

#461 router, backend: replace time.Time with mono-time to optimize duration calculation
  .gitignore
  pkg/manager/router/backend_observer.go
  pkg/manager/router/health_check.go
  pkg/manager/router/metrics.go
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/metrics.go
  pkg/util/monotime/monotime.go
  pkg/util/monotime/monotime_test.go
Labels: lgtm, approved, size/L

#463 *: change some log level from info to debug
  pkg/manager/router/router_score.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/client/client_conn.go
  pkg/proxy/proxy.go
Labels: size/S, lgtm, approved
