Repository pingcap/tiproxy, pull requests merged in 2024-07, with the labels that each got.

#585 metrics, observer: purge backend metrics when backend is down for too long
  pkg/balance/observer/backend_health.go
  pkg/balance/observer/backend_observer.go
  pkg/balance/observer/metrics.go
  pkg/metrics/backend.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: lgtm, approved, size/L

#586 *: update tidb to a newer version
  go.mod
  go.sum
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
  pkg/manager/router/backend_fetcher_test.go
  pkg/metrics/metrics.go
  pkg/proxy/backend/authenticator.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/cmd_processor_exec.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/packetio.go
  pkg/server/api/server.go
Labels: lgtm, approved, size/XXL

#588 elect, infosync: create Election to elect owner
  go.mod
  pkg/manager/elect/election.go
  pkg/manager/elect/election_test.go
  pkg/manager/elect/mock_test.go
  pkg/manager/infosync/etcd.go
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
Labels: lgtm, approved, size/XXL

#590 vip, elect: bind VIP to the active node
  go.mod
  go.sum
  lib/config/proxy.go
  pkg/manager/elect/election.go
  pkg/manager/elect/mock_test.go
  pkg/manager/vip/manager.go
  pkg/manager/vip/manager_test.go
  pkg/manager/vip/mock_test.go
  pkg/manager/vip/network.go
  pkg/manager/vip/network_test.go
  pkg/server/api/config_test.go
Labels: lgtm, approved, size/XXL

#592 server, etcd: integrate vip manager into the server
  pkg/manager/elect/mock_test.go
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
  pkg/manager/vip/network_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/util/etcd/etcd.go
  pkg/util/etcd/etcd_test.go
Labels: lgtm, approved, size/XL

#594 metrics, vip: add metric to show the VIP owner
  pkg/manager/vip/manager.go
  pkg/manager/vip/manager_test.go
  pkg/metrics/grafana/tiproxy_summary.json
  pkg/metrics/grafana/tiproxy_summary.jsonnet
  pkg/metrics/metrics.go
  pkg/metrics/server.go
Labels: lgtm, approved, size/L

#597 metricsreader, observer: read metrics from backend HTTP API
  lib/config/proxy.go
  lib/config/proxy_test.go
  pkg/balance/metricsreader/backend_reader.go
  pkg/balance/metricsreader/backend_reader_test.go
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/mock_test.go
  pkg/balance/metricsreader/query_result.go
  pkg/balance/observer/backend_fetcher.go
  pkg/balance/observer/backend_fetcher_test.go
  pkg/balance/observer/mock_test.go
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
  pkg/manager/vip/manager.go
Labels: lgtm, approved, size/XXL

#601 metricsreader, api: read backend metrics from owner
  pkg/balance/metricsreader/backend_reader.go
  pkg/balance/metricsreader/backend_reader_test.go
  pkg/balance/observer/health_check.go
  pkg/manager/namespace/manager.go
  pkg/server/api/backend.go
  pkg/server/api/backend_test.go
  pkg/server/api/server.go
  pkg/server/api/server_test.go
  pkg/server/server.go
  pkg/util/httputil/http.go
  pkg/util/httputil/http_test.go
Labels: lgtm, approved, size/XXL

#603 balance, httputil: fix the http schema used when sending a `GET` request to server
  pkg/balance/metricsreader/backend_reader.go
  pkg/balance/metricsreader/backend_reader_test.go
  pkg/balance/observer/health_check.go
  pkg/manager/namespace/manager.go
  pkg/server/server.go
  pkg/util/http/http.go
  pkg/util/http/http_test.go
Labels: lgtm, approved, size/L, needs-ok-to-test

#608 http: add comment for explaining the new http cli design and usage
  pkg/util/http/http.go
Labels: size/XS, lgtm, approved, needs-ok-to-test

#606 balance, infosync: support reading metrics from both prometheus and backend
  lib/config/health.go
  lib/config/namespace.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_health_test.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
  pkg/balance/factor/mock_test.go
  pkg/balance/metricsreader/backend_reader.go
  pkg/balance/metricsreader/backend_reader_test.go
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/metrics_reader_test.go
  pkg/balance/metricsreader/mock_test.go
  pkg/balance/metricsreader/prom_reader.go
  pkg/balance/metricsreader/prom_reader_test.go
  pkg/balance/metricsreader/query_result.go
  pkg/manager/elect/election.go
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
  pkg/manager/namespace/manager.go
  pkg/server/server.go
Labels: lgtm, approved, size/XXL

#611 metricsreader, elect: read metrics from zone leader
  lib/config/label.go
  lib/config/proxy.go
  pkg/balance/factor/mock_test.go
  pkg/balance/metricsreader/backend_reader.go
  pkg/balance/metricsreader/backend_reader_test.go
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/metrics_reader_test.go
  pkg/balance/metricsreader/mock_test.go
  pkg/balance/observer/backend_health.go
  pkg/balance/observer/backend_observer_test.go
  pkg/manager/elect/election.go
  pkg/manager/elect/mock_test.go
  pkg/manager/infosync/info.go
  pkg/manager/vip/mock_test.go
  pkg/server/api/backend.go
  pkg/server/api/backend_test.go
  pkg/server/server.go
  pkg/util/etcd/etcd.go
  pkg/util/etcd/etcd_test.go
Labels: lgtm, approved, size/XXL

#613 factor: check the metric interval for CPU and memory-based balance
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_cpu_test.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
  pkg/balance/factor/mock_test.go
Labels: lgtm, approved, size/L

#615 metrics, elect: Show the metrics reader owner on Grafana
  pkg/balance/metricsreader/backend_reader.go
  pkg/manager/elect/election.go
  pkg/manager/elect/election_test.go
  pkg/manager/vip/manager.go
  pkg/manager/vip/manager_test.go
  pkg/metrics/grafana/tiproxy_summary.json
  pkg/metrics/grafana/tiproxy_summary.jsonnet
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/server.go
Labels: lgtm, approved, size/L
