Repository pingcap/tiproxy, pull requests merged in 2024-04, with the labels that each got.

#497 main: add cmd arg `advertise-addr`
  cmd/tiproxy/main.go
Labels: size/XS, lgtm, approved

#496 security: add unit test for cert pool
  lib/util/security/cert_test.go
Labels: lgtm, approved, size/L

#500 metricsreader, infosync: read metrics from prometheus
  lib/config/namespace.go
  pkg/manager/infosync/info.go
  pkg/manager/infosync/info_test.go
  pkg/manager/metricsreader/metrics_reader.go
  pkg/manager/metricsreader/metrics_reader_test.go
  pkg/manager/metricsreader/mock_test.go
  pkg/manager/metricsreader/query_result.go
  pkg/manager/namespace/manager.go
  pkg/manager/router/backend_observer_test.go
  pkg/server/server.go
Labels: lgtm, approved, size/XXL

#504 cmd: deprecate cmd args `log_level` and `log_encoder`
  cmd/tiproxy/main.go
Labels: size/XS, lgtm, approved

#502 router, observer: move BackendObserver from package router to observer
  go.mod
  go.sum
  pkg/manager/metricsreader/metrics_reader.go
  pkg/manager/metricsreader/metrics_reader_test.go
  pkg/manager/metricsreader/mock_test.go
  pkg/manager/namespace/manager.go
  pkg/manager/namespace/namespace.go
  pkg/manager/observer/backend_fetcher.go
  pkg/manager/observer/backend_fetcher_test.go
  pkg/manager/observer/backend_health.go
  pkg/manager/observer/backend_observer.go
  pkg/manager/observer/backend_observer_test.go
  pkg/manager/observer/health_check.go
  pkg/manager/observer/health_check_test.go
  pkg/manager/observer/metrics.go
  pkg/manager/observer/mock_test.go
  pkg/manager/router/metrics.go
  pkg/manager/router/mock_test.go
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/manager/router/router_test.go
  pkg/proxy/net/error.go
  pkg/testkit/main.go
Labels: lgtm, approved, size/XXL

#507 main: make sure the Welcome TiProxy info is always printed.
  pkg/manager/logger/manager.go
  pkg/server/server.go
Labels: size/XS, lgtm, approved, needs-ok-to-test

#508 router, observer: make router pull backends from observer
  pkg/manager/metricsreader/metrics_reader.go
  pkg/manager/namespace/manager.go
  pkg/manager/observer/backend_health.go
  pkg/manager/observer/backend_observer.go
  pkg/manager/observer/backend_observer_test.go
  pkg/manager/router/mock_test.go
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/manager/router/router_test.go
Labels: lgtm, approved, size/XL

#509 balance: move router, observer, and metricsreader to directory balance
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/metrics_reader_test.go
  pkg/balance/metricsreader/mock_test.go
  pkg/balance/metricsreader/query_result.go
  pkg/balance/observer/backend_fetcher.go
  pkg/balance/observer/backend_fetcher_test.go
  pkg/balance/observer/backend_health.go
  pkg/balance/observer/backend_observer.go
  pkg/balance/observer/backend_observer_test.go
  pkg/balance/observer/health_check.go
  pkg/balance/observer/health_check_test.go
  pkg/balance/observer/metrics.go
  pkg/balance/observer/mock_test.go
  pkg/balance/router/backend_selector.go
  pkg/balance/router/metrics.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_static.go
  pkg/balance/router/router_test.go
  pkg/manager/namespace/manager.go
  pkg/manager/namespace/namespace.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/handshake_handler.go
  pkg/proxy/backend/testsuite_test.go
  pkg/proxy/proxy_test.go
Labels: size/S, lgtm, approved

#510 observer: read the server version from HTTP status
  pkg/balance/observer/health_check.go
  pkg/balance/observer/health_check_test.go
  pkg/balance/observer/mock_test.go
Labels: lgtm, approved, size/L, needs-ok-to-test

#512 router: split factors from score-based router
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/metrics_reader_test.go
  pkg/balance/observer/backend_observer.go
  pkg/balance/observer/backend_observer_test.go
  pkg/balance/router/factor.go
  pkg/balance/router/factor_conn.go
  pkg/balance/router/factor_conn_test.go
  pkg/balance/router/factor_health.go
  pkg/balance/router/factor_health_test.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_score_test.go
  pkg/balance/router/router_test.go
Labels: lgtm, approved, size/XXL

#514 observer, router: remove enum BackendStatus
  pkg/balance/observer/backend_health.go
  pkg/balance/observer/backend_observer.go
  pkg/balance/observer/backend_observer_test.go
  pkg/balance/observer/health_check.go
  pkg/balance/observer/health_check_test.go
  pkg/balance/observer/metrics.go
  pkg/balance/router/factor_health_test.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_score_test.go
Labels: lgtm, approved, size/L

#516 metricsreader: fix the metrics_reader.getPromAPI fun panic when there is no prometheus info in pd
  pkg/balance/metricsreader/metrics_reader.go
  pkg/balance/metricsreader/metrics_reader_test.go
Labels: size/S, lgtm, approved, needs-ok-to-test

#518 router, factor: decouple factor with router
  pkg/balance/factor/backend.go
  pkg/balance/factor/backend_test.go
  pkg/balance/factor/factor.go
  pkg/balance/factor/factor_balance.go
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_conn.go
  pkg/balance/factor/factor_conn_test.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_health_test.go
  pkg/balance/factor/mock_test.go
  pkg/balance/policy/balance_policy.go
  pkg/balance/policy/mock_test.go
  pkg/balance/policy/simple_policy.go
  pkg/balance/policy/simple_policy_test.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router.go
  pkg/balance/router/router_score.go
  pkg/balance/router/router_score_test.go
  pkg/manager/namespace/manager.go
Labels: lgtm, approved, size/XXL
