Repository pingcap/tiproxy, pull requests merged in 2025-09, with the labels that each got.

#853 Run modernize on the code
  pkg/balance/factor/factor_balance_test.go
  pkg/balance/factor/factor_conn.go
  pkg/balance/factor/factor_conn_test.go
  pkg/balance/factor/factor_cpu.go
  pkg/balance/factor/factor_health.go
  pkg/balance/factor/factor_health_test.go
  pkg/balance/factor/factor_label.go
  pkg/balance/factor/factor_location.go
  pkg/balance/factor/factor_memory.go
  pkg/balance/factor/factor_memory_test.go
  pkg/balance/factor/factor_status.go
  pkg/balance/factor/mock_test.go
  pkg/balance/metricsreader/backend_reader_test.go
  pkg/balance/metricsreader/prom_reader.go
  pkg/balance/observer/backend_health.go
  pkg/balance/observer/backend_observer_test.go
  pkg/balance/observer/mock_test.go
  pkg/balance/router/mock_test.go
  pkg/balance/router/router_score_test.go
  pkg/manager/config/config_test.go
  pkg/manager/config/namespace_test.go
  pkg/manager/id/manager_test.go
  pkg/manager/infosync/info_test.go
  pkg/manager/logger/manager_test.go
  pkg/manager/namespace/manager.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/net/auth_test.go
  pkg/proxy/net/mysql.go
  pkg/proxy/net/packetio_test.go
  pkg/proxy/net/protocol.go
  pkg/proxy/net/tls_test.go
  pkg/sqlreplay/conn/backend_conn_test.go
  pkg/sqlreplay/conn/conn_test.go
  pkg/sqlreplay/manager/manager_test.go
  pkg/sqlreplay/replay/replay.go
  pkg/sqlreplay/replay/replay_test.go
  pkg/sqlreplay/report/mock_test.go
  pkg/sqlreplay/report/report.go
  pkg/sqlreplay/store/meta_test.go
  pkg/sqlreplay/store/rotate_test.go
  pkg/testkit/main.go
  pkg/util/waitgroup/waitgroup.go
Labels: lgtm, approved, size/L

#858 meter: support metering on next-gen
  go.mod
  go.sum
  lib/config/label.go
  lib/config/proxy.go
  pkg/balance/factor/mock_test.go
  pkg/balance/metricsreader/mock_test.go
  pkg/balance/policy/balance_policy.go
  pkg/balance/policy/mock_test.go
  pkg/balance/router/router.go
  pkg/balance/router/router_static.go
  pkg/manager/meter/meter.go
  pkg/manager/meter/meter_test.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/backend/backend_conn_mgr_test.go
  pkg/proxy/backend/mock_proxy_test.go
  pkg/proxy/client/client_conn.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/server/server.go
  pkg/sqlreplay/conn/backend_conn.go
Labels: lgtm, approved, size/XXL

#860 sqlreplay, api: support replay traffic from plugin-based audit logs
  lib/cli/traffic.go
  pkg/server/api/traffic.go
  pkg/sqlreplay/capture/capture.go
  pkg/sqlreplay/cmd/audit_log_plugin.go
  pkg/sqlreplay/cmd/audit_log_plugin_test.go
  pkg/sqlreplay/cmd/cmd.go
  pkg/sqlreplay/cmd/cmd_test.go
  pkg/sqlreplay/cmd/native.go
  pkg/sqlreplay/cmd/native_test.go
  pkg/sqlreplay/conn/conn.go
  pkg/sqlreplay/manager/job.go
  pkg/sqlreplay/replay/mock_test.go
  pkg/sqlreplay/replay/replay.go
  pkg/sqlreplay/replay/replay_test.go
Labels: lgtm, approved, size/XXL

#861 meter: fix meter data may contain empty data
  pkg/manager/meter/meter.go
  pkg/manager/meter/meter_test.go
Labels: size/XS, lgtm, approved

#863 sqlreplay: deduplicate audit logs and ignore uninitialized statements
  pkg/sqlreplay/cmd/audit_log_plugin.go
  pkg/sqlreplay/cmd/audit_log_plugin_test.go
  pkg/sqlreplay/conn/conn.go
  pkg/sqlreplay/replay/mock_test.go
  pkg/sqlreplay/replay/replay.go
Labels: lgtm, approved, size/L

#869 meter, config: update metering config sdk
  go.mod
  go.sum
  lib/config/proxy.go
  lib/go.mod
  lib/go.sum
  pkg/manager/meter/meter.go
  pkg/manager/meter/meter_test.go
Labels: lgtm, approved, size/XL

#868 sqlreplay: support replaying prepared statements from audit logs
  pkg/proxy/net/mysql.go
  pkg/sqlreplay/cmd/audit_log_plugin.go
  pkg/sqlreplay/cmd/audit_log_plugin_test.go
  pkg/sqlreplay/cmd/cmd.go
  pkg/sqlreplay/cmd/native.go
Labels: lgtm, approved, size/XXL

#872 sqlreplay: fix decoding the SQL_TEXT in audit logs
  pkg/sqlreplay/cmd/audit_log_plugin.go
  pkg/sqlreplay/cmd/audit_log_plugin_test.go
Labels: lgtm, approved, size/M

#877 cmd, sqlreplay: support client mode to replay audit logs
  cmd/replayer/main.go
  pkg/proxy/backend/mock_proxy_test.go
  pkg/server/api/traffic_test.go
  pkg/sqlreplay/capture/capture.go
  pkg/sqlreplay/manager/manager.go
  pkg/sqlreplay/manager/mock_test.go
  pkg/sqlreplay/replay/replay.go
Labels: lgtm, approved, size/L

#878 cmd, replay: filter out the commands before command start time
  cmd/replayer/main.go
  lib/cli/traffic.go
  pkg/server/api/traffic.go
  pkg/sqlreplay/cmd/audit_log_plugin.go
  pkg/sqlreplay/cmd/audit_log_plugin_test.go
  pkg/sqlreplay/cmd/cmd.go
  pkg/sqlreplay/cmd/native.go
  pkg/sqlreplay/cmd/native_test.go
  pkg/sqlreplay/replay/replay.go
Labels: lgtm, approved, size/L

#879 replay: fix report may not be written before close
  pkg/sqlreplay/replay/replay.go
Labels: size/XS, lgtm, approved

#881 replay: implement reading commands from multiple sources
  pkg/sqlreplay/replay/merge_decoder.go
  pkg/sqlreplay/replay/merge_decoder_test.go
  pkg/sqlreplay/replay/replay.go
  pkg/sqlreplay/replay/replay_test.go
Labels: lgtm, approved, size/XL

#886 cmd: break the replayer when received signals
  cmd/replayer/main.go
Labels: size/S, lgtm, approved

#887 expose router rebalance parameters to caller
  .golangci.yaml
  Makefile
  pkg/manager/router/router.go
  pkg/manager/router/router_score.go
  pkg/manager/router/router_test.go
  pkg/proxy/backend/backend_conn_mgr.go
  pkg/proxy/net/capability.go
  pkg/proxy/net/protocol.go
Labels: lgtm, approved, size/M, contribution, ok-to-test

#890 replay, cmd: support ignoring errors in replay
  cmd/replayer/main.go
  lib/cli/traffic.go
  pkg/server/api/traffic.go
  pkg/sqlreplay/replay/mock_test.go
  pkg/sqlreplay/replay/replay.go
  pkg/sqlreplay/replay/replay_test.go
Labels: lgtm, approved, size/M

#897 store: quickly fetch needed file on S3 through Marker
  go.mod
  go.sum
  pkg/sqlreplay/store/rotate.go
  pkg/sqlreplay/store/rotate_test.go
Labels: lgtm, approved, size/XXL

#905 sqlreplay: add logs for replay progress
  pkg/sqlreplay/conn/conn.go
  pkg/sqlreplay/replay/replay.go
  pkg/sqlreplay/replay/replay_test.go
  pkg/sqlreplay/store/rotate.go
Labels: lgtm, approved, size/M

#910 router: fix the cluster_id is wrong in the metering data
  pkg/balance/router/router.go
  pkg/balance/router/router_test.go
Labels: lgtm, approved, size/M

#911 store: fix the issue that marker doesn't have path prefix
  pkg/sqlreplay/store/rotate.go
  pkg/sqlreplay/store/rotate_test.go
Labels: lgtm, approved, size/M

#912 replay: add more fields to replay logs
  pkg/sqlreplay/conn/conn.go
  pkg/sqlreplay/replay/replay.go
Labels: lgtm, approved, size/M

#918 store: add cache for file name and size
  pkg/sqlreplay/store/rotate.go
  pkg/sqlreplay/store/rotate_test.go
Labels: lgtm, approved, size/L

#919 meter: update metering sdk
  go.mod
  go.sum
  pkg/manager/meter/meter.go
  pkg/manager/meter/meter_test.go
Labels: size/S, lgtm, approved
